import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import DarkModeToggle from "./darkMode";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import AuthProvider from "@/provider/AuthProvider";
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Blog Site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <div className=" m-auto  container dark:bg-black dark:text-white text-black   bg-white">
            <Navbar />
            <div className="max-w-[900px] m-auto">{children}</div>
            <Footer />
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
